#!/bin/bash
############################################################
#
#	Password Generator (pwdGen) v1.2
#	Developed by BijanEbrahimi - 2012
#		<myopensourceprojects@gmail.com>
#		Released Under GPL v.3 License
#	For More information please README ;)
#
############################################################

STRING=""
STRING_CONFIRM=" "
while [[ ! $STRING == $STRING_CONFIRM ]]; do
	echo -n "Please Enter your fixed String [for safty it'll be invisible]: "
	read -s STRING
	echo -en "\n"
	echo -n "Confirm: "
	read -s STRING_CONFIRM
	echo -e "\n"
done

SALT=""
echo -n "Please Enter a Salt String (e.g DOMAIN name): "
read SALT

START=""
while [[ ! $START =~ ^[0-9]+$ ]]; do
    	echo -n "Please Enter Begining Point [0-43]: "
   	read START
done
END=""
while [[ ! $END =~ ^[0-9]+$ ]]; do
    	echo -n "Please Enter Ending Point [1-44]: "
    	read END
done

QUERY=$(echo "$STRING$SALT" | md5sum | grep -o "[a-z0-9]*" | base64 )
# or $(echo "$STRING$SALT" | openssl md5 | base64 ) for shorter version

echo "PASSWORD: ${QUERY:$START:$END}"
